# Generated by Django 3.2.7 on 2021-09-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('postal_address', models.CharField(max_length=100)),
                ('studioname', models.CharField(max_length=50)),
                ('price', models.BigIntegerField(max_length=10)),
                ('instagram_id', models.CharField(max_length=50)),
                ('facebook_id', models.CharField(max_length=50)),
            ],
        ),
    ]
